### PR TITLE
Fixed bug #23 : QA could hung when stopping trace session

### PR DESCRIPTION
**Pull request by hvlad**

### CODE REVIEW

**Comment by hvlad** [comment]
Any problem with this PR ?

**Review by pcisar — COMMENTED** [review]
Do you understand it correctly that proposed change do not even try to stop the trace session properly? If that's the case, is it because the srv.trace.stop() call hangs or throws an exception?

**Comment by hvlad** [comment]
> Do I understand it correctly that proposed change do not even try to stop the trace session properly? 

It signal `trace_thread` to break poll loop and disconnect from services manager - it stops trace session properly.

**Comment by pavel-zotov** [comment]
Merged after talk with Vlad and Alex.

**Pull request merged**
